# Generated by Django 3.1 on 2020-10-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBlog', '0002_journey_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journey',
            old_name='image',
            new_name='image_journey',
        ),
    ]
