# Generated by Django 3.1 on 2020-10-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBlog', '0003_auto_20201012_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journey',
            old_name='image_journey',
            new_name='image',
        ),
    ]
