# Generated by Django 3.1 on 2020-10-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBlog', '0004_auto_20201012_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='journey_pics')),
            ],
        ),
        migrations.RemoveField(
            model_name='journey',
            name='image',
        ),
    ]
