# Generated by Django 3.1 on 2020-10-12 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TravelBlog', '0005_auto_20201012_1830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JourneyProfile',
        ),
        migrations.AddField(
            model_name='journey',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='journey_pics'),
        ),
    ]
